server:
  port: 8061

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.bce

spring:
  application:
    name: discovery-server
  output:
    ansi:
      enabled: always

#management:
#  tracing:
#    sampling:
#      probability: 1.0